### ISSUE TITLE
cannot import name 'core_heclib' from 'pydsstools._lib.x64'

### ISSUE THREAD

**Issue by dhah229** [gyanz/pydsstools#41]
I am hitting an import error
```
>>> from pydsstools.heclib.dss import HecDss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dhah\Documents\pydsstools\pydsstools\heclib\dss\HecDss.py", line 15, in <module>
    from ...core import Open as _Open
  File "C:\Users\dhah\Documents\pydsstools\pydsstools\core\__init__.py", line 28, in <module>
    from .._lib import *
  File "C:\Users\dhah\Documents\pydsstools\pydsstools\_lib\__init__.py", line 1, in <module>
    from .x64 import core_heclib
ImportError: cannot import name 'core_heclib' from 'pydsstools._lib.x64' (C:\Users\dhah\Documents\pydsstools\pydsstools\_lib\x64\__init__.py)
```
Using Python 3.7 pydsstools installed using .whl file.
Thank you

**Comment by dhah229** [comment]
Fresh install worked.
