### ISSUE TITLE
cannot import core heclib

### ISSUE THREAD

**Issue by Hooshyar94** [gyanz/pydsstools#46]
Hi gyanz,
I am trying to import HecDss by using the following command:

```
from pydsstools.heclib.dss import HecDss
```
and this is the error that I am getting:
```
Traceback (most recent call last):

  File "C:\Smart Detention Storage\Simple_model\Simple_1\test1.py", line 2, in <module>
    from pydsstools.heclib.dss import HecDss

  File "C:\Smart Detention Storage\Simple_model\Simple_1\pydsstools\heclib\dss\HecDss.py", line 15, in <module>
    from ...core import Open as _Open

  File "C:\Smart Detention Storage\Simple_model\Simple_1\pydsstools\core\__init__.py", line 28, in <module>
    from .._lib import *

  File "C:\Smart Detention Storage\Simple_model\Simple_1\pydsstools\_lib\__init__.py", line 1, in <module>
    from .x64 import core_heclib

ImportError: cannot import name 'core_heclib' from 'pydsstools._lib.x64' (C:\Smart Detention Storage\Simple_model\Simple_1\pydsstools\_lib\x64\__init__.py)
```
Would you please help me with that? I think a file is missing from x64.

**Comment by danhamill** [comment]
I would try an uninstall and reinstall.

**Comment by gyanz** [comment]
I would recommend you to install the library using one of the wheels. I think you are using the source code directly.

**Comment by Hooshyar94** [comment]
Initially I was cloning it, or trying to install it manually, but python wasn't able to identify it as library, so I installed it through using the wheel and the problem was solved. Thanks.
