### ISSUE TITLE
Support for numpy version >= 2

### ISSUE THREAD

**Issue by bzindovic** [gyanz/pydsstools#60]
For now, it seems that pydsstools works with numpy < 2 and I have to downgrade numpy to 1.26.4 (it seems to be the last working for me). As Numpy version 2 introduces some breaking changes, are there any plan to support it?

**Comment by bzindovic** [comment]
For reference, these are the steps to reproduce this problem:
```
import pydsstools
from pydsstools.heclib.dss import HecDss
```
and got this as output:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py311\Lib\site-packages\pydsstools\heclib\dss\HecDss.py", line 15, in <module>
    from ...core import Open as _Open
  File "C:\py311\Lib\site-packages\pydsstools\core\__init__.py", line 28, in <module>
    from .._lib import *
  File "C:\py311\Lib\site-packages\pydsstools\_lib\__init__.py", line 1, in <module>
    from .x64 import core_heclib
  File "pydsstools\src\core_heclib.pyx", line 1, in init pydsstools._lib.x64.core_heclib
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by Caojunisstudying** [comment]
I have downgraded my numpy to 1.26.4, the same problem keeps coming, I don't know how to fix it!!!

**Comment by mylesmc123** [comment]
pip install "numpy<2.0" worked for me to get past this error, but after I also uninstalled pydsstools and reinstalled it, all via pip, as well.

**Comment by gyanz** [comment]
I don’t plan to support numpy 2 for Python 3.12 or earlier. For Python 3.13 and later, numpy 2 will be supported, though I’m not sure when. I haven’t used version 2 myself, so I would appreciate any feedback on parts of the code that may need to be changed to support it.

**Comment by gyanz** [comment]
The beta release 3.0.0b5 supports numpy 2 on Python 3.13+.
