### ISSUE TITLE
pytimes error, hour must be in 0..23

### ISSUE THREAD

**Issue by lucas1867** [gyanz/pydsstools#7]
I've been having trouble with the library when trying to plot a time series with the midnight hour in it, since HEC-RAS uses 24:00 for it and python doesn't recognize it. With a startDate, endDate of:

["29JAN2019 21:30:00", "30JAN2019 05:30:00"]

I get this error when running `times = np.array(ts.pytimes)`

`dateutil.parser._parser.ParserError: hour must be in 0..23: 29 Jan2019 24:00:00`

I was wondering if the code takes that into account or maybe I'm making a mistake. If the time series spans in a single day before 00:00 there's no problem. I'm using version 1.3 with python 3.6
Thanks!

**Comment by MikeNeilson** [comment]
Check if your plotting library supports a date formatting character of k or K or has any discussion of the 2400 hour. Th k character often used to represent the 24:00 time if a library supports it. However, it isn't well supported by most date libraries.
 
Otherwise you could convert the HEC Times to UNIX time and insert that into your numpy array. If your plotting library won't take UNIX time directly use the python time module to reformat to something it will. It would then show up on your plot as 30Jan2019 00:00.

Unfortunately I don't see a built in function in the DSS library to do so. HEC time is kept in minutes since 01Jan1900 (not timezone specified) if that helps.

**Comment by lucas1867** [comment]
Mike, thank you for your answer.
The thing is the array obtained from the DSS by pydsstools, `ts.pytimes`, is not a callable object in the python environment, and I cannot convert the datetime format. Even typing `print(ts.pytimes)` gets me an error

```
Traceback (most recent call last):
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 1241, in _build_naive
    naive = default.replace(**repl)
ValueError: hour must be in 0..23

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hectime.pyx", line 130, in core_heclib.getPyDateTimeFromString
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: hour must be in 0..23: 29Jan2019 24:00:00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 1241, in _build_naive
    naive = default.replace(**repl)
ValueError: hour must be in 0..23

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<pyshell#53>", line 1, in <module>
    print(ts.pytimes)
  File "time_series.pyx", line 168, in core_heclib.TimeSeriesStruct.pytimes.__get__
  File "hectime.pyx", line 164, in core_heclib.getPyDateTimeFromValue
  File "hectime.pyx", line 151, in core_heclib.getPyDateTimeFromString
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "...\Python36\lib\site-packages\dateutil\parser\_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: hour must be in 0..23: 29 Jan2019 24:00:00

```

**Comment by gyanz** [comment]
ts.pytimes uses getPyDateTimeFromString function from hectime.pyx. This function is supposed to convert any date with 2400 hours to python compatible date, i.e., next day with 0000 hours. Unfortunately, I won't be able to look into this until I am back from vacation next week.

**Comment by gyanz** [comment]
@lucas1867 Can you check your script with the latest version (1.4)?

**Comment by lucas1867** [comment]
@gyanz I can confirm it works just fine in version 1.4. Thank you!
